services:
  flask:
    build: .
    container_name: flask_esports
    ports:
      - "8000:8000"
    environment:
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    volumes:
      - .:/app
      - ./instance/site.db:/app/instance/site.db


  nginx:
    image: nginx:stable-alpine
    container_name: nginx_reverse_proxy
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/yourdomain.com/fullchain.pem:/etc/ssl/certs/wildcard.crt:ro
      - /etc/letsencrypt/live/yourdomain.com/privkey.pem:/etc/ssl/private/wildcard.key:ro
    depends_on:
      - flask
